### ISSUE TITLE
0.80 result for no second string

### ISSUE THREAD

**Issue by BHushanRathod** [bcse/stringscore#4]
why there is base result of 0.80 even though no any second string is passed.

**Comment by bcse** [comment]
I didn't design the algorithm. I only port them to Python, so I don't know why compare with empty string returns 0.8. Maybe you should ask the original author.

See original [liquidmetal usage](https://github.com/rmm5t/liquidmetal#usage):
`LiquidMetal.score("Foo Bar", "")      //=> 0.8`

And quicksilver will return 0.9.
https://github.com/quicksilver/Quicksilver/blob/master/Quicksilver/Code-QuickStepFoundation/NSString_BLTRExtensions.m#L57
