### ISSUE TITLE
result always in between 0.8 to 1.0

### ISSUE THREAD

**Issue by BHushanRathod** [bcse/stringscore#5]
whenever i passed two strings, matching result is always in between 0.8 to 1.0
why there is no result lesser than 0.80 like 0.20 or 0.50

>>> liquidmetal.score('abcd','ab')
0.95
>>> liquidmetal.score('abcd','abc')
0.975
>>> liquidmetal.score('abcd','abcd')
1.0
>>> liquidmetal.score('abcd','zxy')
0.0
>>> liquidmetal.score('abcd','')
0.8

**Comment by bcse** [comment]
```
>>> liquidmetal.score('abcde','a')
0.9199999999999999
>>> liquidmetal.score('abcde','b')
0.68
>>> liquidmetal.score('abcde','c')
0.52
>>> liquidmetal.score('abcde','d')
0.36
>>> liquidmetal.score('abcde','e')
0.2
```

Now you may wondering why they have different results. It's because the algorithm is designed for auto-completion, not for string similarity.
